[project]
name = "fly-in"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "josuesamba99@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[tool.uv]
package = false

[dependency-groups]
dev = [
    "flake8>=7.4.1",
    "mypy>=2.3.1",
]


